# Define target output
target: vcs

# Define target part
export PRJ_PART = XCKU040-FFVA1156-2-E

# Define Firmware Version Number
export PRJ_VERSION = 0x00000001

# Define the TOP_DIR path
export TOP_DIR = $(abspath $(PWD)/../..)

# Use top level makefile
include $(TOP_DIR)/submodules/ruckus/system_vivado.mk
